removed beatsPerMinute
moddevices/modguis pull request #2
Opened 2017-11-06 17:30 UTC by JWBverheesen

2017-11-06 17:52 UTC, jesseverhage requested changes
Please change the following points to get an approved pull request:
1. don't remove the BPM designation from Scape, it does use BPM units.
2. remove the DubDelay.ttl changes until the cause of the issues with this particular plugin is known.

Thank you!

2017-11-08 12:07 UTC, odurc requested changes

2017-11-08 12:07 UTC, odurc commented on plugins-fixed/mod-mda-DubDelay.lv2/DubDelay.ttl
> +        lv2:designation time:beatsPerMinute;
This line need to be removed as well

2017-11-08 12:21 UTC, odurc approved these changes

2017-11-08 15:47 UTC, jesseverhage approved these changes

2017-11-08 15:48 UTC, merged